kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: tracecat-db
spec:
  enableSuperuserAccess: false
  instances: 1
  bootstrap:
    initdb:
      database: tracecat-db
      owner: tracecat
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
