apiVersion: v1
kind: ConfigMap
metadata:
  name: tracecat-config
data:
  LOG_LEVEL: "INFO"
  TRACECAT__APP_ENV: "production" # not yet configurable, not sure if that would make sense?
  TRACECAT__AUTH_TYPES: "basic,google_oauth" # not yet configurable
  TRACECAT__DB_SSLMODE: "require" # not sure?
  TRACECAT__API_ROOT_PATH: "/api"
#---
#kind: Cluster
#apiVersion: postgresql.cnpg.io/v1
#metadata:
#  name: tracecat-db
#spec:
#  enableSuperuserAccess: false
#  instances: 1
#  bootstrap:
#    initdb:
#      database: tracecat
#      owner: tracecat
#  storage:
#    size: 2Gi
#  monitoring:
#    enablePodMonitor: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracecat-api
  labels:
    app.kubernetes.io/name: tracecat-api
spec:
  selector:
    matchLabels:
      app: tracecat-api
  template:
    metadata:
      labels:
        app: tracecat-api
    spec:
#      initContainers:
#        - name: service-key-generator
#          image: busybox:1.30
#          command: [ 'sh', '-c', 'openssl rand -hex 32' ]
      containers:
        - name: tracecat-api
          image: "ghcr.io/tracecathq/tracecat:0.9.0"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: tracecat-db-app
            - configMapRef:
                name: tracecat-config
          env:
            - name: TRACECAT__DB_URI
              value: "postgresql+psycopg://$(username):$(password)@$(host):$(port)/$(dbname)"
            - name: RUN_MIGRATIONS
              value: "true"
            - name: TRACECAT__PUBLIC_RUNNER_URL
              valueFrom:
                configMapKeyRef:
                  name: tracecat-config
                  key: PUBLIC_API_URL
            - name: TRACECAT__ALLOW_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: tracecat-config
                  key: PUBLIC_APP_URL
            - name: TRACECAT__PUBLIC_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: tracecat-config
                  key: PUBLIC_APP_URL
            - name: TRACECAT__PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: tracecat-config
                  key: PUBLIC_API_URL
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: tracecat-api
#spec:
#  ports:
#    - port: 8000
#      name: tracecat-api
#  selector:
#    app: tracecat-api
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: tracecat
#spec:
#  rules:
#    - host: tracecat.local # TODO take from env/configmap
#      http:
#        paths:
#          - path: /api
#            pathType: Prefix
#            backend:
#              service:
#                name: tracecat-api
#                port:
#                  number: 8000
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: tracecat-ui
#                port:
#                  number: 3000
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: tracecat-ui
#  labels:
#    app.kubernetes.io/name: tracecat-ui
#spec:
#  selector:
#    matchLabels:
#      app: tracecat-ui
#  template:
#    metadata:
#      labels:
#        app: tracecat-ui
#    spec:
#      containers:
#        - name: tracecat-ui
#          image: "ghcr.io/tracecathq/tracecat-ui:0.9.0"
#          ports:
#            - containerPort: 3000
#          envFrom:
#            - configMapRef:
#                name: tracecat-config
#          env:
#            - name: NODE_ENV
#              valueFrom:
#                configMapKeyRef:
#                  name: tracecat-config
#                  key: TRACECAT__APP_ENV
#            # Important: environment variables prefixed with `NEXT_PUBLIC_` are exposed to the browser client
#            - name: NEXT_PUBLIC_APP_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: tracecat-config
#                  key: PUBLIC_APP_URL
#            - name: NEXT_PUBLIC_API_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: tracecat-config
#                  key: PUBLIC_API_URL
#            - name: NEXT_PUBLIC_APP_ENV
#              valueFrom:
#                configMapKeyRef:
#                  name: tracecat-config
#                  key: TRACECAT__APP_ENV
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: tracecat-ui
#spec:
#  ports:
#    - port: 3000
#      name: tracecat-ui
#  selector:
#    app: tracecat-ui
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: tracecat-worker
#  labels:
#    app.kubernetes.io/name: tracecat-worker
#spec:
#  selector:
#    matchLabels:
#      app: tracecat-worker
#  template:
#    metadata:
#      labels:
#        app: tracecat-worker
#    spec:
#      containers:
#        - name: tracecat-worker
#          image: "ghcr.io/tracecathq/tracecat:0.9.0"
#          command: ["python", "tracecat/dsl/worker.py"]
#          envFrom:
#            - secretRef:
#                name: tracecat-db-app
#            - configMapRef:
#                name: tracecat-config
#          env:
#            - name: TRACECAT__DB_URI
#              value: "postgresql+psycopg://$(username):$(password)@$(host):$(port)/$(dbname)"
